spring.application.name=BACKEND-VELOXA

# Variable para elegir la base de datos: mysql o sqlserver
app.database=mysql

# Configuracion principal para DataSource (usada por Hibernate)
spring.datasource.url=jdbc:mysql://localhost:3306/veloxa_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuracion para SQL Server (alternativa)
spring.datasource.sqlserver.url=jdbc:sqlserver://localhost:1433;databaseName=velotax_db;encrypt=true;trustServerCertificate=true
spring.datasource.sqlserver.username=sa
spring.datasource.sqlserver.password=
spring.datasource.sqlserver.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Configuracion para MySQL
spring.datasource.mysql.url=jdbc:mysql://localhost:3306/veloxa_db?useSSL=false&serverTimezone=UTC
spring.datasource.mysql.username=root
spring.datasource.mysql.password=
spring.datasource.mysql.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate Configuration
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
